### ISSUE TITLE
apt-get -qq -y install git curl build-essential 단계에서 에러.

### ISSUE THREAD

**Issue by onesup** [nacyot/docker-moniwiki#1]
``` bash````
onesup@onesup64:~/docker-moniwiki$ sudo docker build -t nacyot/moniwiki .
[sudo] password for onesup: 
Sending build context to Docker daemon  59.9 kB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:12.04
ubuntu:12.04: The image you are pulling has been verified
ed52aaa56e98: Pull complete 
b875af6dcb23: Pull complete 
41959ee20b93: Pull complete 
f959d044ebdf: Pull complete 
511136ea3c5a: Already exists 
Status: Downloaded newer image for ubuntu:12.04
 ---> f959d044ebdf
Step 1 : MAINTAINER Daekwon Kim <propellerheaven@gmail.com>
 ---> Running in f4f69c2fa932
 ---> baf123035a78
Removing intermediate container f4f69c2fa932
Step 2 : RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
 ---> Running in 1293dac44e3b
 ---> 15c44000dc70
Removing intermediate container 1293dac44e3b
Step 3 : RUN apt-get update
 ---> Running in 72751d9074d8
Hit http://archive.ubuntu.com precise Release.gpg
Hit http://archive.ubuntu.com precise Release
Get:1 http://archive.ubuntu.com precise/main amd64 Packages [1640 kB]
Get:2 http://archive.ubuntu.com precise/universe amd64 Packages [6167 kB]
Get:3 http://archive.ubuntu.com precise/main i386 Packages [1641 kB]
Get:4 http://archive.ubuntu.com precise/universe i386 Packages [6180 kB]
Fetched 15.6 MB in 18s (829 kB/s)
Reading package lists...
 ---> 2bb6db5552b8
Removing intermediate container 72751d9074d8
Step 4 : RUN apt-get -qq -y install git curl build-essential
 ---> Running in c4608d7af4e9
E: Unable to correct problems, you have held broken packages.
INFO[0063] The command [/bin/sh -c apt-get -qq -y install git curl build-essential] returned a non-zero code: 100 
onesup@onesup64:~/docker-moniwiki$ 
```

**Comment by onesup** [comment]
`docker run` 으로 들어가서 직접 실행을 시켜보니 디펜던시 에러가 발생합니다.
이게 일반적인 우분투 환경에서는 알아서 디펜던시를 해결해주는걸로 알고 있는데 신기하네요.
libc6-dev 를 설치하려고 하면 또 디펜던시가 걸리고, 해당 디펜던시 요인을 설치해주려고 하면 또 걸리고,
하다보면 순환으로 걸려서 해결이 안되는 문제가 발생합니다.

```
root@7b3ec7250979:/# apt-get install build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 build-essential : Depends: libc6-dev but it is not going to be installed or
                            libc-dev
                   Depends: g++ (>= 4:4.4.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@7b3ec7250979:/#
```

**Comment by nacyot** [comment]
1. ubuntu 12.04는 deprecated 되어, 패키지 관리에 문제가 있을 가능성이 높습니다.
2. 사실 이 이미지에는 build-essential이 필요하지 않습니다. 

Dockerfile 일부 수정해서 작동하도록 만들어뒀으니 참고해주세요. 

https://github.com/nacyot/docker-moniwiki/commit/cde6a60dd7cdb84530dcb70dca9a6ff1f93a3d6d

**Comment by onesup** [comment]
헉... 이렇게 빨리... 
감사합니다!! ^^
:+1:
